apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.211.135
    path: "/data/nfs"