version: "3.7"
services:
  sops:
    image: mozilla/sops:latest
    container_name: "sops"    
    environment:
      - DEPLOY_MODE=3  # Cambia según sea necesario (iniciar/encriptar/desencriptar)
    command: /bin/bash -c "/startup.sh"
    volumes:
      - ./secrets:/secrets
      - ./sops:/sops
      - ./startup.sh:/startup.sh:ro

  #Contenedor Postgres

  postgres:
      image: "postgres:11.6"
      container_name: "postgres"     
      depends_on:
          sops:
              condition: service_completed_successfully      
      ports:
          - "5432:5432"
      environment:
          TZ: 'America/Argentina/Buenos_Aires' 
      env_file:
          - ./secrets/postgres.env           
      volumes:
          - vol-postgres3:/var/lib/postgresql/data  
          - ./docker/postgres/db:/docker-entrypoint-initdb.d  
      restart: always
      networks:
          - sistemas

#Definicion de volumen para postgres
volumes:
  vol-postgres3:
    driver: local 

#Configuracion de Red para contenedores
networks:
  sistemas:
    driver: bridge 
